export const IMPACT_MEDIA_MAX_WIDTH = 700;
export const IMPACT_MEDIA_MAX_HEIGHT = 500;
export const IMPACT_IMAGE_MAX_SIZE_MB = 5;
export const IMPACT_VIDEO_MAX_SIZE_MB = 20;
export const IMPACT_IMAGE_COMPRESSION_QUALITY = 0.82;

export const IMPACT_IMAGE_MAX_SIZE_BYTES = IMPACT_IMAGE_MAX_SIZE_MB * 1024 * 1024;
export const IMPACT_VIDEO_MAX_SIZE_BYTES = IMPACT_VIDEO_MAX_SIZE_MB * 1024 * 1024;
